### ISSUE TITLE
[BUG] malformed manifest

### ISSUE THREAD

**Issue by ippocratis** [DADi590/V.I.S.O.R.---A-real-assistant--Android-Client#1]
**Describe the bug** 
Application fails to install.
Android package manager throws error failed to install malformed manifest
SAI is a bit more informative and says
heavy-weight applications can not have process in main process
Malformed manifest at binary XML.line 205

**How to reproduce** 
Install with package manager or SAI

**Device information (please complete it):** 
 - Device: [redmi note 9s]
 - OS: [sparkos android 13]
 - App version [e.g. v2021_12_29]

**Additional information** 
moving apk to system/priv-apps wont help either.

**Comment by Edw590** [comment]
Hi! Sorry, not sure why that happened. I was actually going to make a new release with the changes I've made so far to the app (a year it seems), so this just gave me another reason. Can you try the latest one and see if it works? It should, I think - it worked on the Android Studio emulator.

**Comment by ippocratis** [comment]
The 2022_12_29 version installs fine
Thanks
looking forward to check out what the app can do

**Comment by Edw590** [comment]
Cool! But just a heads up, it doesn't have much still. I'd love to put more things on it (I have various in mind and written on the TODO file), but.... time 😅. I don't have enough to do it as fast as I'd like.

You won't see it do much from just the UI alone though. The majority of it is with the commands you can give it, and what it does internally to make those commands work (with time, UI will be created and more commands added, and other things).

Also I've just added something very useful to the readme that I thought I already had there, but maybe I didn't: the supported commands. If you need anything about how to check them, say something. I'll improve this with an improvement coming. That improvement might make me able to answer VISOR if it asks a question (so far one can only order things, not answer).

**Comment by Edw590** [comment]
Hi. Just decided to warn you that I released a new version with a list of commands that can be sent to the app, voice or text (just because it wasn't easily possible to know what could be said to the app and now is, in case you'd like to know). Cheers!
