### ISSUE TITLE
Repeated error warnings, had to uninstall

### ISSUE THREAD

**Issue by nigelp** [DADi590/V.I.S.O.R.---A-real-assistant--Android-Client#2]
android install. "Attention module restarted, system checker". Repeated constantly even when the app is switched off. Had to uninstall it immediately. :)

**Comment by Edw590** [comment]
Oh! I forgot! Damn me. You have to go to the Home screen and allow all permissions. Then it will stop saying those things. Damn. I'll put a note on the Releases.

**Comment by nigelp** [comment]
You need to do more than that, sir. I can't uninstall the app at all. It refuses. Not a good look. Advice?

**Comment by nigelp** [comment]
Also, I cannot terminate the app either. It just keeps telling me my Android version (V 13) is not supported. The commands function is disabled, I keep getting that annoying voice telling me that long press is not supported, root access is not active, and a couple of other things. It's actually scarily out of control, which is interesting. :)

**Comment by Edw590** [comment]
I'm sorry you're having those problems. I'm trying the app on that Android version now on the emulator (I only have up to Android 8 on physical devices).

But to uninstall the app you have to disable the Device Administrator mode first. The app is prepared to try to refuse to uninstall, but it won't refuse forever. Only twice. In those 2 times it will lock your phone. You just have to unlock it and keep saying Yes to disable the Device Admin mode.

I took this idea from an antivirus, to have the app be prepared as a very secure app that you can't uninstall mega easily (in the future it's supposed to have theft protection. This is part of that).

**Comment by nigelp** [comment]
Heh, finally got it uninstalled after going through every permission to disable. It was rather like that scene in 2001:Space Odyssey, where he's switching off H.A.L. Every time I started switching off a permission that voice would go, 'warning, permissions are...' and then cut off as I switched off the permission. Every time, for all the permissions. Hilarious! 

I think you need to spend a bit of time testing this. And definitely it needs HUGE amounts more documentation. I've never seen such a massive number of settings. :)

**Comment by Edw590** [comment]
The app is supposed to be used alongside the PC apps. Just the phone app doesn't give you all the features. And the PC app is the documented one. It has About tabs for each screen to explain what each does. The Android app is more to be used after having used the PC one which explains everything (I've put a note about that now).

Though the Android app can also be used with the features it has - to talk with VISOR to give him commands. The voice stops talking after you hear all it has to say (you can also skip speeches in the Speech screen though). But with the server app working you can do the rest it allows.

At least with me it seems to work just fine. I'm not sure why it didn't work well with you. Here it seems to work.
